name: Build Demo App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  gtDemo_Image:
    uses: feenkcom/gtoolkit-custom-app/.github/workflows/app-image.yml@main
    with: 
      app_name: 'GtDemo'
      pharo_load_script_path: 'scripts/st/load-project.st'
      pharo_test_packages: 'GtDemoApp'
      pharo_release_line_handler: 'releaseDemoApp'
      pharo_release_version_line_handler: 'printDemoAppVersion'
      git_user_name: 'Juraj Kubelka'
      git_user_email: 'juraj.kubelka@feenk.com'
    secrets:
      gt_releaser_ssh_key: ${{ secrets.FEENK_RELEASER_SSH_PRIVATE_KEY }}

  Release_gtDemo_Image: 
    uses: feenkcom/gtoolkit-custom-app/.github/workflows/release-artifacts.yml@main
    needs: 
      - gtDemo_Image
    with:
      artifacts: ${{ needs.gtDemo_Image.outputs.release_zip }} 
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
