name: Build Demo App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  gtDemo_Image:
    uses: feenkcom/gtoolkit-custom-app/.github/workflows/app-image.yml@main
    with: 
      app_name: 'GtDemo'
      pharo_load_script_path: 'scripts/st/load-project.st'
      pharo_test_packages: 'GtDemoApp'
      pharo_release_line_handler: 'releaseDemoApp'
      pharo_release_version_line_handler: 'printDemoAppVersion'
      git_user_name: 'Juraj Kubelka'
      git_user_email: 'juraj.kubelka@feenk.com'
    secrets:
      gt_releaser_ssh_key: ${{ secrets.FEENK_RELEASER_SSH_PRIVATE_KEY }}
  

  release_gtDemo_Image:
    runs-on: ubuntu-20.04
    needs: 
      - gtDemo_Image
    steps: 
      # We need the SSH key to load code from private repositories and/or run GT Releaser
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
          ssh-keyscan sftp.feenk.com >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.FEENK_RELEASER_SSH_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
          ssh-add /home/runner/.ssh/github_actions

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          name: ${{ needs.gtDemo_Image.outputs.release_zip }}
          path: ${{ needs.gtDemo_Image.outputs.release_zip }}

      - name: Download All Artifacts
        uses: actions/download-artifact@v3
      - name: Upload
        run: |
          chmod +x ./scripts/github/*.sh
          ls -lah
          ./scripts/github/create-github-release.sh github_api_token=${{ secrets.GITHUB_TOKEN }} owner=feenkcom repo=gtoolkit-demo-app tag=${{ needs.gtDemo_Image.outputs.release_version }}
          ./scripts/github/upload-github-release.sh github_api_token=${{ secrets.GITHUB_TOKEN }} owner=feenkcom repo=gtoolkit-demo-app tag=${{ needs.gtDemo_Image.outputs.release_version }} filename=${{ needs.gtDemo_Image.outputs.release_zip }}